# https://quarto.org/docs/books/book-output.html
# https://quarto.org/docs/projects/profiles.html
project:
  pre-render:
    - scripts/pracs-pre.py
  post-render:
    - scripts/pracs-post.py
  output-dir: _answers 
  render:
    - "*.qmd"
    - "practicals/"
    - "!practicals/fragments/"
    - "!practicals/fragments/*.ipynb"
    - "!assessments"
    - "!data/"
    - "!lectures/"
    - "!sessions/"
    - "!setup/"
    - "!ref/"
    - "!help.qmd"
    - "!references.qmd"
    - "!index.qmd"
  resources:
    - "img/"
    - "practicals/img/"
    - "!assessments"
    - "!data/"
    - "!lectures/"
    - "!sessions/"
    - "!setup/"
    - "!ref/"
qna:
  ipynb: question
  html: question
  pdf: answer
