# https://quarto.org/docs/books/book-output.html
project:
  pre-render:
    - scripts/pracs.py
  post-render:
    - scripts/pracs.py
  output-dir: _pracs 
  render:
    - "*.qmd"
    - "practicals/"
    - "!practicals/fragments/"
    - "!practicals/fragments/*.ipynb"
    - "!assessments/"
    - "!data/"
    - "!lectures/"
    - "!sessions/"
    - "!setup/"
    - "!ref/"
    - "!help.qmd"
    - "!references.qmd"
    - "!index.qmd"
  resources:
    - "img/"
    - "practicals/img/"
    - "!assessments/"
    - "!data/"
    - "!lectures/"
    - "!sessions/"
    - "!setup/"
    - "!ref/"
format:
  ipynb:
    number-sections: true
    shift-heading-level-by: 1
    #freeze: true
    #cache: true # Not compatible with inline expressions
  pdf:
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=25mm
      - bottom=25mm
      - heightrounded
    number-sections: true
    toc: true
    toc-depth: 1
    colorlinks: true
    highlight-style: github
    mainfont: "Spectral"
    sansfont: "Roboto Flex"
    monofont: "Roboto Flex"
