project:
  pre-render:
    - scripts/web.py
  post-render:
    - scripts/web.py
format:
  html:
    theme: 
      - minty
      - css/web.scss
    code-copy: true
    code-link: true
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true