# https://quarto.org/docs/books/book-output.html
project:
  pre-render:
    - scripts/pre.py
  post-render:
    - scripts/post.py
  type: website
  output-dir: _site
  preview:
    port: 4200
  render:
    - "*.qmd"
  resources:
    - "bib/"
    - "img/"
    - "!data/"
execute:
  freeze: auto

metadata-files:
  - _website.yml

qna:
  ipynb: question
  html: question
  pdf: question

format:
  html:
    theme:
      - minty
      - css/web.scss
    code-copy: true
    code-link: true
    code-overflow: wrap
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true

bibliography: ref/Readings.bib
csl: ref/chicago-author-date.csl

highlight-style: pygments
