# https://quarto.org/docs/books/book-output.html
project:
  pre-render:
    - scripts/pre.py
  post-render:
    - scripts/post.py
  type: website
  output-dir: _site
  preview:
    port: 4200
  render:
    - "*.qmd"
    - "!bib/"
    - "!data/"
    - "!practicals/"
  resources:
    - "bib/"
    - "img/"
    - "data/"
execute:
  freeze: auto

metadata-files:
  - _website.yml

bibliography: ref/Readings.bib
csl: ref/chicago-author-date.csl

highlight-style: pygments
